@baseUrl = http://localhost:8080
@accessToken = INSERT_ACCESS_TOKEN
@refreshToken = INSERT_REFRESH_TOKEN
@userId = 27


### 1. Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "Ahmad",
  "password": "password34"
}


### 2. Log in and receive a JWT
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "Ahmad",
  "password": "password34"
}


### 3. Access the authenticated user's dashboard
GET {{baseUrl}}/auth/dashboard
Authorization: Bearer {{accessToken}}


### 4. View the authenticated user's profile
GET {{baseUrl}}/auth/profile
Authorization: Bearer {{accessToken}}


### 5. Access the admin settings
GET {{baseUrl}}/auth/admin-settings
Authorization: Bearer {{accessToken}}


### 6. Get all users
GET {{baseUrl}}/auth/users
Authorization: Bearer {{accessToken}}


### 7. Change a user's role to ADMIN
# Set @userId to an existing user ID
PATCH {{baseUrl}}/auth/users/{{userId}}/role
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "role": "ROLE_ADMIN"
}


### 8. Change a user's role back to USER
# Set @userId to an existing user ID
PATCH {{baseUrl}}/auth/users/{{userId}}/role
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "role": "ROLE_USER"
}


### 9. Delete a user
# Set @userId to an existing user ID
DELETE {{baseUrl}}/auth/users/{{userId}}
Authorization: Bearer {{accessToken}}

### Test cors!
OPTIONS {{baseUrl}}/auth/register
Origin: http://localhost:4040
Access-Control-Request-Method: POST
Access-Control-Request-Headers: Content-Type
#response should be:
#Access-Control-Allow-Origin: http://localhost:4040
#Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
#Access-Control-Allow-Headers: Authorization, Content-Type

### refresh token
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### logout
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### To test login with Google, open:
#http://localhost:8080/oauth2/authorization/google
#You will be redirected to Google to authenticate. After a successful login, Google redirects you to:
#http://localhost:8080/login/oauth2/code/google
#Spring Security processes the callback, and the application returns its own access token and refresh token.
